#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port8,           driveFL,       tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////
//
//  Runs a motor and datalogs the RPM at speed increments of five
//  so we can use the data later to make a mathematical function
//              converting motor speed to RPM
//
//////////////////////////////////////////////////////////////////


//The current RPM Value
float RPMValue = 0.0;

//How often the RPM is read in milliseconds
float RPMReadRate = 5000.0;

task main()
{
	//Loop through motor speeds at increments of five
	for(int i = 125; i >= -125; i-=5){
		//set the motor
		motor[driveFL] = i;
		//wait the amount of seconds delay for the RPM reading
		wait1Msec((int)RPMReadRate);
		//read the current tick amount
		long tickCount = nMotorEncoder[driveFL];
		//Calculate the RPM
		RPMValue = ((tickCount*(60000.0/RPMReadRate))/627.2);
		//Reset the motor encoder (this eliminates the need for a last ticks variable, since it would just be 0)
		nMotorEncoder[driveFL] = 0;
		//Log out the motor speed and RPM value
		datalogDataGroupStart();
		datalogAddValue(1,i);
		datalogAddValue(2,RPMValue);
		datalogDataGroupEnd();
	}
}
