#pragma config(Sensor, dgtl11, driveTest,      sensorQuadEncoder)
#pragma config(Motor,  port10,          testMotor,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl11)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{

}

float rpm = 0.0;

task readRPM() {
	motor[testMotor] = 127;
	while(true) {
		resetMotorEncoder(testMotor);
		wait1Msec(5000);
		rpm = (nMotorEncoder[testMotor]/360.0) * 12.0;
	}
}

task usercontrol()
{
	bLCDBacklight = true;
	startTask( readRPM );
	string debug = "";
  while (true)
  {
  	sprintf(debug,"%d",rpm);
		displayLCDString(0,0,debug);
  }
}
