#pragma config(Sensor, in1,    powerExpander,  sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c" // Competition includes [DO NOT TOUCH]
#include "sensors.c" // General sensor methods
#include "auton.c" // Autonomous controller
#include "lcd.c" // LCD methods

#define VERSION_MAJOR = 1
#define VERSION_MINOR = 0
#define VERSION_BUILD = 0
#define VERSION_TYPE = "ALPHA"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          			 2616E Starstruck
//
// Welcome to the 2616E Starstruck program.
//
/////////////////////////////////////////////////////////////////////////////////////////
//
// Pinmap: https://drive.google.com/open?id=1mSrSJ1BPUzoXAdo2x8ED-OwT-OZY7r5Y9P7FmuNDcLY
// Controller map: // TODO Add link
// Trello: https://trello.com/b/oXrKvfA7/2616e-starstruck
//
// - Ask Cameron if you need/want permission to any of the above sites
// - Please keep these up-to-date when you do any pins or buttons.
// - Make sure you notify builders if you change ports up, and drivers if buttons!
// - The maps above [hopefully] will hopefully be printed on every release version for reference
//   -> and stored in the team boxes.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          			  Pre-Autonomous
//
// - Set up general methods
// - Get rid of compiler errors we don't need to see
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	bStopTasksBetweenModes = true; // Tasks stop when we need them to. Not doing this can be dangerous.
	bLCDBacklight = true; // Turn our LCD backlight on

	// Never passing if statement. Lets us get rid of compile warnings so we can focus on the ones we need to see.
	if (false) {
		UserControlCodePlaceholderForTesting();
		AutonomousCodePlaceholderForTesting();
		sensorsErrorEscape(); // Get rid of unused methods for the sensor lib
		// Feel free to add currently un-used methods/tasks here if you're sure they are meant to not be used.
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// TODO Write what we [personally] do here
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	runAuton(); // auton.c
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// TODO Write what we [personally] do here
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	lcdInit(); // Starts all tasks for handling the lcd. Check lcd.c
	while (true)
	{
		// Hopefully we can offload a lot of the work here to seperate files, and just run a checkX() method for each
		UserControlCodePlaceholderForTesting();
		// The following are not tasks for the reason we want them to run sequentially, not parallel.
	}
}
